from __future__ import annotations

import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Union

__all__ = ["TimelineClip", "concatenate_clips", "concatenate_shots_stream_copy"]

PathLike = Union[str, Path]


@dataclass
class TimelineClip:
    """One Shot placed on a Scene/Episode timeline, with optional in/out trim points."""

    path: str
    trim_start_sec: Optional[float] = None
    trim_end_sec: Optional[float] = None
    shot_id: Optional[str] = None


def _to_clip(item: Union[PathLike, TimelineClip]) -> TimelineClip:
    if isinstance(item, TimelineClip):
        return item
    return TimelineClip(path=str(item))


def _run(cmd: List[str]) -> None:
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"ffmpeg command failed: {' '.join(cmd)}\n{result.stderr}")


def concatenate_clips(
    clips: List[Union[PathLike, TimelineClip]],
    output_path: PathLike,
    width: int = 1080,
    height: int = 1920,
    fps: int = 30,
    audio_sample_rate: int = 44100,
) -> Path:
    """Concatenates Shot clips (optionally trimmed) into one Scene/Episode timeline video.

    Re-encodes every clip to a common resolution/fps/sample-rate before the concat
    filter, so it works even when shots were generated by different models/pipelines
    with mismatched codecs -- unlike the ffmpeg concat *demuxer*, which requires
    identical stream parameters.
    """
    timeline = [_to_clip(c) for c in clips]
    if not timeline:
        raise ValueError("clips must contain at least one item")
    for clip in timeline:
        if not Path(clip.path).exists():
            raise FileNotFoundError(f"Shot clip not found: {clip.path}")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    cmd: List[str] = ["ffmpeg", "-y"]
    for clip in timeline:
        if clip.trim_start_sec is not None:
            cmd += ["-ss", f"{clip.trim_start_sec:.3f}"]
        if clip.trim_end_sec is not None:
            duration = clip.trim_end_sec - (clip.trim_start_sec or 0.0)
            cmd += ["-t", f"{duration:.3f}"]
        cmd += ["-i", str(clip.path)]

    filter_parts = []
    for i in range(len(timeline)):
        filter_parts.append(
            f"[{i}:v]scale={width}:{height}:force_original_aspect_ratio=decrease,"
            f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps={fps}[v{i}];"
            f"[{i}:a]aresample={audio_sample_rate},aformat=channel_layouts=stereo[a{i}];"
        )
    concat_inputs = "".join(f"[v{i}][a{i}]" for i in range(len(timeline)))
    filter_complex = "".join(filter_parts) + f"{concat_inputs}concat=n={len(timeline)}:v=1:a=1[outv][outa]"

    cmd += [
        "-filter_complex",
        filter_complex,
        "-map",
        "[outv]",
        "-map",
        "[outa]",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        str(output_path),
    ]
    _run(cmd)
    return output_path


def concatenate_shots_stream_copy(
    shot_paths: List[PathLike],
    output_path: PathLike,
) -> Path:
    """Fast path: stream-copy concat via the ffmpeg concat demuxer. Only valid when all
    shots already share identical codec/resolution/fps (e.g. all rendered by the same
    generation pipeline pass); raises no error otherwise but ffmpeg may reject the output.
    Prefer concatenate_clips() unless you know the inputs are homogeneous.
    """
    if not shot_paths:
        raise ValueError("shot_paths must contain at least one item")
    for p in shot_paths:
        if not Path(p).exists():
            raise FileNotFoundError(f"Shot clip not found: {p}")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False) as f:
        for p in shot_paths:
            f.write(f"file '{Path(p).resolve()}'\n")
        list_path = f.name

    try:
        cmd = [
            "ffmpeg",
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            list_path,
            "-c",
            "copy",
            str(output_path),
        ]
        _run(cmd)
    finally:
        Path(list_path).unlink(missing_ok=True)
    return output_path
