"""init schema

Revision ID: f7d0958c1f12
Revises:
Create Date: 2026-09-09 21:47:53.987870

第一版表结构（alembic autogenerate 生成）：projects / characters / episodes / scenes / shots / assets 六张表，
主键都是 36 位 uuid，每张表只有少量标量列，还没有 JSON ``data`` 列。
这版对应 v0.1 "数据库只登记素材"的阶段；v0.2 把 03_STRUCTURED_DATA 对象接进数据库的改动在下一个迁移
a3c9e1d2f4b5 里。保留这一版是为了已经部署的库能按顺序升级，不要手改它。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# alembic 用的版本标识：本迁移的 id，以及它基于哪个版本（None = 链条起点）
revision: str = 'f7d0958c1f12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级：建六张基础表。建表顺序按外键依赖：projects 最先，assets（引用其它四张表）最后。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('characters',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_image_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('episodes',
    sa.Column('episode_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_table('scenes',
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('episode_id', sa.String(length=36), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ),
    sa.PrimaryKeyConstraint('scene_id')
    )
    op.create_table('shots',
    sa.Column('shot_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('video_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.scene_id'], ),
    sa.PrimaryKeyConstraint('shot_id')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=True),
    sa.Column('episode_id', sa.String(length=36), nullable=True),
    sa.Column('shot_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.shot_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚：按建表的逆序删表（先删引用别人的 assets，最后删 projects），否则外键约束会挡住。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    op.drop_table('shots')
    op.drop_table('scenes')
    op.drop_table('episodes')
    op.drop_table('characters')
    op.drop_table('projects')
    # ### end Alembic commands ###
